### ISSUE TITLE
what's the status of this project?

### ISSUE THREAD

**Issue by rkonda** [ooyala/atlantis-supervisor#46]
Rajesh here. I am curious if there is a demo of this project. It's cool to be able to configure an environment and manage different versions of different services. Is this project under active development? There is no readme or wiki.

**Comment by edanaher** [comment]
Yes, we're using this at Ooyala and continuing work on it, but we've been spending most of our time fighting with internal issues and configuration, so the external progress is less visible.

And better documentation is in progress; see https://github.com/ooyala/atlantis/tree/add-readme for a start.

**Comment by rkonda** [comment]
Whats your email address Evan? Mine is rkonda@gmail
